name: gaelmv
description: "practicas"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  camera: ^0.11.1
  path: ^1.8.0
  geolocator: ^10.0.0
  image_picker: ^1.0.4
  geocoding: ^2.0.0
  flutter_map: ^2.0.0
  latlong2: ^0.8.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  positioned_tap_detector_2: ^1.0.3
  permission_handler: ^11.0.0
  awesome_notifications: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
